#!/bin/bash

alias e='/Applications/MacVim.app/Contents/MacOS/Vim -g --remote-silent'
alias v='/Applications/MacVim.app/Contents/MacOS/Vim'
alias o=open

alias ls='ls -GF'
alias ll='ls -lah'

alias pu='pushd $(pwd)'
alias po='popd'

alias g='git'

alias schanges="svn st | grep \"^[A|M]\""
alias snew="svn st | grep \"^?\""

alias remove_cache='cd tools/ && ./remove_cache && cd ..'

alias gfame='git  ls-tree -r HEAD | cut -f 2 | grep -E '\.php$' | xargs -n1 git blame --line-porcelain | grep "^author " | sort | uniq -c | sort -nr | sed  "s/ author//"'

# find the 10 largest files in the current directory
alias flarge='find . -type f -print0 | xargs -0 du -s | sort -n | tail -10 | cut -f2 | xargs -I{} du -sh {}'
