#!/bin/bash

alias c=./app/console
alias e=mvim
alias g=git
alias o=open

alias ls='ls -GF'
alias ll='ls -hlGFa'

alias pu='pushd $(pwd)'
alias po='popd'

alias todo='cat ~/Documents/todo'

alias schanges="svn st | grep \"^[A|M]\""
alias snew="svn st | grep \"^?\""

alias remove_cache='cd tools/ && ./remove_cache && cd ..'

# TODO make alias 'fame' in .gitconfig when '\.php' matching is not hardcoded.
alias gfame='git  ls-tree -r HEAD | cut -f 2 | grep -E '\.php$' | xargs -n1 git blame --line-porcelain | grep "^author " | sort | uniq -c | sort -nr | sed  "s/ author//"'

# find the 10 largest files in the current directory
alias flarge='find . -type f -print0 | xargs -0 du -s | sort -n | tail -10 | cut -f2 | xargs -I{} du -sh {}'

# TODO days => hours [=> minutes [=> seconds]]
# TODO configurable dates?
alias daystill="python -c 'from datetime import date; print \"Nog %sX slapen.\" % (date(2015,10,23) - date.today()).days'"
