#!/bin/bash

alias apache-restart='sudo apachectl restart'
alias release='~/Code/Scripts/release.sh'

alias e=mvim
alias o=open
alias t=tmux

# wijs-project-creator
alias npr=/Volumes/Sites/tools/wijs-project-creator/npr
alias secure=/Volumes/Sites/tools/wijs-project-creator/secure
alias secure2=/Volumes/Sites/tools/wijs-project-creator/secure2

# sneakers
alias sneakers='cd /Users/tommy/code/sneakers'

# sleep
alias sleep="diskutil unmount disk$(diskutil list | grep storage | sed 's/.*disk\([^ ]*\).*/\1/') && diskutil unmount disk$(diskutil list | grep backup | sed 's/.*disk\([^ ]*\).*/\1/') && pmset sleepnow"

# history timestamp
HISTTIMEFORMAT="$BLUE%d/%m/%y %T $NORMAL"

# git
alias g=git

alias ls='ls -GF'
alias ll='ls -hlGFa'
alias gls='function __mygls() { echo "$BLUE git log --date=relative --pretty=format:\"$YELLOW%h $GREEN%an$NORMAL %s $BLUE\" -n ${*:-10} $NORMAL" && git log --date=relative --pretty=format:"$YELLOW%h $GREEN%an$BLACK %s" -n ${*:-10}}; unset -f __mygls; }; __mygls'
alias glst='function __myglst() { echo "$BLUE git log --date=relative --pretty=format:\"%ad $YELLOW%h $GREEN%an$NORMAL %s $BLUE\" -n ${*:-10} $NORMAL" && git log --date=relative --pretty=format:"%ad $YELLOW%h $GREEN%an$BLACK %s" -n ${*:-10}}; unset -f __mygls; }; __myglst'

alias pu='pushd $(pwd)'
alias po='popd'

alias schanges="svn st | grep \"^[A|M]\""
alias snew="svn st | grep \"^?\""

alias remove_cache='cd tools/ && ./remove_cache && cd ..'

# TODO make alias 'fame' in .gitconfig when '\.php' matching is not hardcoded.
alias gfame='git  ls-tree -r HEAD | cut -f 2 | grep -E '\.php$' | xargs -n1 git blame --line-porcelain | grep "^author " | sort | uniq -c | sort -nr | sed  "s/ author//"'

# find the 10 largest files in the current directory
alias flarge='find . -type f -print0 | xargs -0 du -s | sort -n | tail -10 | cut -f2 | xargs -I{} du -sh {}'

# TODO days => hours [=> minutes [=> seconds]]
# TODO configurable dates?
alias daystill="python -c 'from datetime import date; print \"Nog %sX slapen.\" % (date(2014,11,21) - date.today()).days'"

# on startup shell do
startup
