#!/bin/bash

#
# Bash functions
# self-written, copied, adapted...
# If not written myself, I probably took/stole/adapted it from
# Gary Bernhardt, Jan Moesen, Dave Lens, or some other dude(tte) on the web.
#

#
# cd to the directory the Finder is in.
# By @sindresorhus taken from:
# https://github.com/paulirish/dotfiles/commit/e67d1bc03
#
cdf() {
    cd "`osascript -e 'tell app "Finder" to POSIX path of (insertion location as alias)'`"
}


#
# Attach to an existing tmux session, create the session if it doesn't exist.
#
dev() {
    local project=$1
    local switch=""

    if [[ "$project" == "" ]]
    then
        echo "usage: dev <project>"
        return 1
    fi

    # Depending on whether or not we are already in a tmux session (this is why
    # we check for $TMUX before it is created later on), we need to switch to
    # that session differently.
    if [[ "$TMUX" == "" ]]; then
        switch='tmux attach -t'
    else
        switch='tmux switch-client -t'
    fi

    tmux has-session -t $project > /dev/null 2>&1
    if [ $? != 0 ]; then
        TMUX= tmux_create_dev_session $project
    fi

    $switch $project
}


#
# Create a new tmux session for developing.
#
tmux_create_dev_session() {
    pushd `pwd`
    local project=$1

    if [ -d ~/Projects/$project ]; then
        path=~/Projects/$project
    elif [ -d ~/Sites/$project ]; then
        path=~/Sites/$project
    else
        echo "$project not found, exiting (TODO: offer to create it?)"
        return 1
    fi

    # Start relative from the project path; we don't have to send 'cd $path' to
    # the tmux sessions.
    cd $path

    tmux new-session -s $project -d
    tmux new-window -n console -t $project

    # TODO Make cross-language (by find...[php|py|rb|pl|...]?)
    tmux send-keys -t "$project:console" "clear && php -a" C-m

    tmux select-window -t "$project:1"
    popd
}


#
# Start a new fork project in the current directory.
# @param string github url
# @param string branch of the fork repo to use.
#
fork_start() {
    local giturl=$1
    local forkbranch=$2

    if [[ "$giturl" == "" ]] || [[ "$forkbranch" == "" ]]
    then
        echo "usage: fork_start <giturl> <forkbranch>"
    else
        # first awk gets the 'projectname.git' part, second awk 'projectname'
        project=$(echo $giturl | awk -F"/" '{print $NF}' | awk -F"." '{print $1}')
        if [[ "$project" == "" ]]
        then
            echo "Could not get the project name from $giturl... exiting"
            return 1;
        else
            git clone $giturl
            cd $project
            git remote add upstream git://github.com/forkcms/forkcms.git
            git pull upstream $forkbranch
            git push origin master
        fi
    fi
}


#
# Upload a screenshot to imgur "on the fly":
# Let user select region, take screenshot
# Upload screenshot to imgur.com
# Print resulting url to image.
#
# @see http://api.imgur.com/examples
#
imgur() {
    # API Key provided by Alan@imgur.com
    local api_key="b3625162d3418ac51a9ee805b1840452"
    local url_api_upload="http://api.imgur.com/2/upload.xml"

    local fn_image="/tmp/screenshot-`date +%Y-%m-%d-%H-%M-%S`.png"
    screencapture -ix $fn_image
    local response=`curl -s -F "image=@$fn_image" -F "key=$api_key" $url_api_upload`
    echo $response | tail -1 | sed -E 's/.*<original>(.*)<\/original>.*/\1/'
}


#
# Execute vagrant commands in the sneakers directory
# Because we don't want to symlink the vagrantfile in every project and we don't
# want to go wandering away from our project root directory.
#
sneakers() {
    cd ~/Projects/sneakers
    vagrant $*
    cd - > /dev/null
}


#
# Create an SSH config host entry and add my public key to that host.
#
# @param The identifier to use for this SSH host configuration.
# @param The host name.
# @param The username for that host.
#
ssh_configure_host() {
    local identifier=$1
    local hostname=$2
    local username=$3

    if [[ "$identifier" == "" ]] || [[ "$username" == "" ]] || [[ "$hostname" == "" ]]
    then
        echo "usage: ssh_configure_host <identifier> <hostname> <username>"
    else
        echo -e "Host $identifier\n\tHostName $hostname\n\tUser $username\n\tIdentityFile ~/.ssh/id_rsa\n\tForwardAgent yes" >> ~/.ssh/config
        ssh $identifier 'mkdir -p .ssh && cat >> ~/.ssh/authorized_keys' < ~/.ssh/id_rsa.pub
        # TODO Use ssh_test_key()?
        tput bold; ssh -o PasswordAuthentication=no $identifier true && { tput setaf 2; echo 'Success!'; } || { tput setaf 1; echo 'Failure'; }; tput sgr0
        ssh_load_autocomplete
    fi
}


#
# adds ~/.ssh/config to the ssh autocomplete
# Call whenever ssh host config changes (@see ssh_configure_host)
#
ssh_load_autocomplete() {
    complete -W "$(awk '/^\s*Host\s*/ { sub(/^\s*Host /, ""); print; }' ~/.ssh/config)" ssh
}


#
# Test a giveh ssh_config host identifier.
#
ssh_test_key() {
    local identifier=$1
    ssh -o PasswordAuthentication=no $identifier true && { tput setaf 2; echo 'Success!'; } || { tput setaf 1; echo 'Failure'; }; tput sgr0
}


#
# Update Vim plugins
#
vup() {
    pushd `pwd`
    cd ~/.vim
    ./update
    echo
    echo "Use 'popd' to go back to the directory you were in."
    echo "TODO: Check if anything changed and auto commit plugin by plugin."
    echo
}
