#!/bin/bash

function __glink(){
	{ git remote show origin | grep Push | awk '{ print $3 }' | sed 's/github.ncube.be:/https:\/\/github.ncube.be\//' | sed 's/git@//' | sed 's/\.git/\/commit\//'; git rev-parse ${1:-$(git log -n 1 | head -n 1 | git rev-parse --short $(awk '{ print $2 }'))};  } | sed -e 'N;s/\n//'
}

alias glink='__glink'

# git
alias g=git
# alias gls='function __mygls() { echo "$BLUE git log --date=relative --pretty=format:\"$YELLOW%h $GREEN%an$NORMAL %s $BLUE\" -n ${*:-10} $NORMAL" && git log --date=relative --pretty=format:"$YELLOW%h $GREEN%an$BLACK %s" -n ${*:-10}}; unset -f __mygls; }; __mygls'
# alias glst='function __myglst() { echo "$BLUE git log --date=relative --pretty=format:\"%ad $YELLOW%h $GREEN%an$NORMAL %s $BLUE\" -n ${*:-10} $NORMAL" && git log --date=relative --pretty=format:"%ad $YELLOW%h $GREEN%an$BLACK %s" -n ${*:-10}}; unset -f __mygls; }; __myglst'
alias branchvso='/Users/tommy/Dotfiles/bakpak/bin/git-branches-vs-origin-master'
alias branchvsc='/Users/tommy/Dotfiles/bakpak/bin/git-current-branch-is-behind-origin-master.sh'
