#!/bin/bash

# git
alias g=git
alias gls='function __mygls() { echo "$BLUE git log --date=relative --pretty=format:\"$YELLOW%h $GREEN%an$NORMAL %s $BLUE\" -n ${*:-10} $NORMAL" && git log --date=relative --pretty=format:"$YELLOW%h $GREEN%an$BLACK %s" -n ${*:-10}}; unset -f __mygls; }; __mygls'
alias glst='function __myglst() { echo "$BLUE git log --date=relative --pretty=format:\"%ad $YELLOW%h $GREEN%an$NORMAL %s $BLUE\" -n ${*:-10} $NORMAL" && git log --date=relative --pretty=format:"%ad $YELLOW%h $GREEN%an$BLACK %s" -n ${*:-10}}; unset -f __mygls; }; __myglst'
