#!/bin/bash

source ~/.bash_completion/project-completion.bash
alias csp=csproject
csproject() {
    ROOT=${CSPROJECTROOT}
    DIRECTORY=$1
    echo "$BLUE change dir to project '$ROOT$DIRECTORY' $NORMAL"
    if [ -d "$ROOT$DIRECTORY" ]; then
        cd "$ROOT$DIRECTORY"
    else
        echo "$RED Dir '$ROOT$DIRECTORY' does not exist! Taking you to root instead. $NORMAL"
        cd $ROOT
    fi
}
