#!/bin/bash

# NPR script needs NPR_DOCROOT
NPR_DOCROOT='/Volumes/Sites/'

# Add property of wijs doc block

addpropertyofwijsto(){
	find $1 -type f -name '*.php' | while read f; do if [[ $(head -n 11 $f | tr '\n' ' ' | sed 's/ //g' | grep '<?phpnamespace') ]]; then cat $f | sed -i.bak -e 's/<?php/<?php\
\
\/\*\*\
\ * This file is property of Wijs.be\
\ *\
\ * For the full copyright and license information, please view the license\
\ * file that was distributed with this source code.\
\ *\//' $f && rm -rf $f'.bak'; fi; done;
}

# Prepare gulp for a project
# see: https://github.com/getchopstick/chopstick-boilerplate
makereadythegulp (){
	gem update --system
	gem install bundler
	bundle install
	npm install -g bower
	bower install
	npm install -g gulp
	npm install
}

# Get a public key from one of your colleagues.
# @param personal_access_token The key you've set in github.
# @param username The username for which you want to get the key.
get_public_key (){
    local personal_access_token=$1
    local username=$2

    if [[ "$personal_access_token" == "" ]] || [[ "$username" == "" ]]
    then
        echo "usage: get_public_key <personal_access_token> <username>"
    else
		# echo "Getting public key for user $2…"
		curl -s -u tommyvandevelde:$personal_access_token https://github.ncube.be/api/v3/users/$username/keys | grep key | awk -F':' '{ print $2}' | sed 's/"//g' | xargs echo
    fi
}
