#!/bin/bash

# NPR script needs NPR_DOCROOT
NPR_DOCROOT='/Volumes/Sites/'

# Add property of wijs doc block

addpropertyofwijsto(){
	find $1 -type f -name '*.php' | while read f; do if [[ $(head -n 11 $f | tr '\n' ' ' | sed 's/ //g' | grep '<?phpnamespace') ]]; then cat $f | sed -i.bak -e 's/<?php/<?php\
\
\/\*\*\
\ * This file is property of Wijs.be\
\ *\
\ * For the full copyright and license information, please view the license\
\ * file that was distributed with this source code.\
\ *\//' $f && rm -rf $f'.bak'; fi; done;
}

# Prepare gulp for a project
# see: https://github.com/getchopstick/chopstick-boilerplate
makereadythegulp (){
	gem update --system
	gem install bundler
	bundle install
	npm install -g bower
	bower install
	npm install -g gulp
	npm install
}
